# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TanakaContours
                                 A QGIS plugin
 Generates Tanaka contours from DEM
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-06-10
        copyright            : (C) 2022 by Richard Moritz
        email                : richi.moritz.rm@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TanakaContours class from file TanakaContours.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .tanaka_contours import TanakaContours
    return TanakaContours(iface)
